name: 'OpenAI Chat on Issues'
description: 'This is a GitHub Actions for running OpenAI''s chat in GitHub Issues.'
author: 'Hiroyuki Kusu'
branding:
  icon: 'aperture'
  color: 'yellow'
inputs:
  openai-key:
    description: ''
    required: true
  model:
    description: ''
    required: false
    default: 'gpt-3.5-turbo'
  system-prompt:
    description: ''
    required: false
  history:
    description: ''
    required: false
    default: '10'
  event-name:
    description: ''
    required: false
    default: ${{ github.event_name }}
  event:
    description: ''
    default: ${{ toJson(github.event) }}
    required: false
  github-token:
    description: ''
    required: false
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
