name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-tasks:
    name: Run npm tasks
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run tasks
        run: |
          npm ci
          npm run check-all
      - name: Check dist directory for no changes # dist/index.js のコミットが漏れていないか
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" != '0' ]; then
            echo 'Changes detected.'
            exit 1
          fi
  use-action:
    name: Use this action for check
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Use this action
        id: match
        uses: ./
        with:
          openai-key: ${{ secrets.OPENAI_KEY }}
          event-name: 'issues'
          event: |
            {
              "action": "opened",
              "issue": {
                "number": 1,
                "state": "open",
                "body": "Hello, who are you?"
              },
              "repository": {
                "full_name": "${{ github.repository }}"
              }
            }
